# Generated by Django 3.2 on 2021-06-01 01:05

import author_review.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20210522_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('abstract', models.TextField()),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('content', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核不通过')], default=0)),
                ('article_address', models.FileField(upload_to=author_review.models.file_directory_path)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'tb_categories',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'tb_writers',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '审稿人',
                'verbose_name_plural': '审稿人',
                'db_table': 'tb_reviewers',
            },
        ),
        migrations.CreateModel(
            name='ArticleWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.article')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.writer')),
            ],
            options={
                'verbose_name': '文章-作者关系表',
                'verbose_name_plural': '文章-作者关系表',
                'db_table': 'article-writer-relation',
            },
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未提交评论'), (1, '已提交评论')], default=0)),
                ('author_review', models.TextField(blank=True)),
                ('create_time', models.DateField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.reviewer')),
            ],
            options={
                'verbose_name': '文章-审稿人关系表',
                'verbose_name_plural': '文章-审稿人关系表',
                'db_table': 'article-reviewer-relation',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(through='author_review.ArticleReview', to='author_review.Reviewer'),
        ),
        migrations.AddField(
            model_name='article',
            name='writers',
            field=models.ManyToManyField(through='author_review.ArticleWriter', to='author_review.Writer'),
        ),
    ]
