# Generated by Django 3.2 on 2021-06-11 18:01

import author_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_review', '0002_auto_20210611_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_address',
            field=models.FileField(blank=True, upload_to=author_review.models.file_directory_path),
        ),
    ]
