# Generated by Django 3.2 on 2021-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_review', '0006_auto_20210616_0044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='tb_activity',
        ),
    ]
