# Generated by Django 3.2 on 2021-06-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('author_review', '0007_alter_activity_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '修改了文章'), (1, '修改成功了文章'), (2, '提交了文章'), (3, '成功发布了文章'), (4, '审核了文章'), (5, '删除了文章')], default=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '文章动态表',
                'verbose_name_plural': '文章动态表',
                'db_table': 'tb_news',
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
