# Generated by Django 3.2 on 2021-06-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_review', '0008_auto_20210616_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleNews',
        ),
    ]
