# Generated by Django 3.2 on 2021-06-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('author_review', '0009_delete_articlenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_review.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '文章动态表',
                'verbose_name_plural': '文章动态表',
                'db_table': 'tb_activity',
            },
        ),
    ]
