# Generated by Django 3.2 on 2021-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_review', '0010_actactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='actactivity',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '修改了文章'), (1, '修改成功了文章'), (2, '提交了文章'), (3, '成功发布了文章'), (4, '审核了文章'), (5, '删除了文章')], default=2),
        ),
    ]
