# Generated by Django 3.2 on 2021-06-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlereview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
