# Generated by Django 3.2 on 2021-06-09 16:51

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('avatar', models.ImageField(blank=True, upload_to=user.models.user_avatar_directory_path)),
                ('user_desc', models.CharField(blank=True, max_length=500)),
                ('real_name', models.CharField(blank=True, max_length=128)),
                ('education_exp', models.CharField(blank=True, max_length=500)),
                ('job_unit', models.CharField(blank=True, max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('reader', '读者'), ('author_review', '作者'), ('reviewer', '审稿人'), ('edit', '编辑')], default='读者', max_length=32)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_users',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '用户收藏的文章',
                'verbose_name_plural': '用户收藏的文章',
                'db_table': 'user_collect',
            },
        ),
    ]
