# Generated by Django 3.2 on 2021-05-22 08:43

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210520_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAuthor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isEditor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isReviewer',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reader', '读者'), ('author_review', '作者'), ('reviewer', '审稿人'), ('edit', '编辑')], default='读者', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=user.models.user_avatar_directory_path),
        ),
    ]
